- name: ensure unzip is installed
  apt:
    name: unzip
    state: present

- name: Fetch elasticsearch source archive search version.
  get_url:
    dest: "/tmp/{{ es_pkg_name}}.tar.gz"
    url: "https://download.elasticsearch.org/elasticsearch/elasticsearch/{{ es_pkg_name }}.tar.gz"
    force: "{{ es_force_archive_dl | default(omit) }}"

- name: untar the elasticsearch source archive
  unarchive:
    remote_src: yes
    src: "/tmp/{{ es_pkg_name }}.tar.gz"
    dest: /tmp
    mode: 0755

- name: Check and see if the elasticsearch dir has been created
  stat:
    path: /usr/share/elasticsearch
  register: es_home

- name: Copy the unarchived elasticsearch to main directory
  command: "mv /tmp/{{ es_pkg_name }} /usr/share/elasticsearch"
  when: not es_home.stat.exists

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml
    dest: /usr/share/elasticsearch/elasticsearch.yml
    mode: 0750
    force: yes
  notify: restart elasticsearch

- name: install elastic search service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: elasticsearch.service, dest: /lib/systemd/system/elasticsearch.service }
  tags:
    - elasticsearch-service

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Check and see if the elasticsearch dir has been created
  stat:
    path: /usr/share/elasticsearch/plugins/analysis-icu
  register: icu_plugin

- name: Install the ICU plugin
  command: "/usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.5.0"
  when: not icu_plugin.stat.exists

- name: Make sure Elasticsearch is running
  wait_for:
    host: "{{ es_network_host }}"
    port: "{{ es_http_port }}"
    delay: 3
    timeout: 300
